name: "TEST: Run pytest using tox"
on:
  push:
  pull_request:
  schedule:
    - cron: '0 7 * * 1'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install
      - name: Test with pytest
        run: |
          poetry run tox -e py
